In [14]:
import pandas as pd
import numpy as np
import csv as csv
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
#from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.externals import joblib

In [3]:

data = pd.read_csv('./syntheticData.csv')
X, y = data.iloc[:, 1:], data.iloc[:,0]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, stratify=y)

"""
Now use scikit-learn's MLP classifier to train the model.
"""
clf = MLPClassifier()
clf = clf.fit(X_train, y_train)

"""
Serialize Model
"""
joblib.dump(clf, 'model/mlp.pkl')

/Users/pcowe/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


['model/mlp.pkl']

In [16]:
# Model Evaluation
predictions = clf.predict(X_test)

#Precision, recall, fscore, accuracy

#print(classification_report(y_test, predictions))

#AUC
from sklearn.metrics import precision_recall_fscore_support

In [26]:

#print(clf.classes_)

In [25]:
from sklearn.preprocessing import label_binarize

y = label_binarize(y_train, classes=clf.classes_)
#n_classes = y.shape[1]

print(y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
fpr, tpr, thresholds = metrics.roc_curve(y, predictions)
metrics.auc(fpr, tpr)

NameError: name 'label_binarize' is not defined